#ifndef PIN_CONFIG_H
#define PIN_CONFIG_H

#include "board_config_2560.h"
#include "avr_gpio.h"

/// GPIO pin mappings from Arduino MEGA pins to exercise 3 circuit
#define BUTTON_FLOOR_1_PORT IO_22_PORT
#define BUTTON_FLOOR_1_DIRECTION IO_22_DIRECTION
#define BUTTON_FLOOR_1_INPUT IO_22_INPUT
#define BUTTON_FLOOR_1_PIN IO_22_PIN

#define BUTTON_FLOOR_2_PORT IO_23_PORT
#define BUTTON_FLOOR_2_DIRECTION IO_23_DIRECTION
#define BUTTON_FLOOR_2_INPUT IO_23_INPUT
#define BUTTON_FLOOR_2_PIN IO_23_PIN

#define BUTTON_FLOOR_3_PORT IO_24_PORT
#define BUTTON_FLOOR_3_DIRECTION IO_24_DIRECTION
#define BUTTON_FLOOR_3_INPUT IO_24_INPUT
#define BUTTON_FLOOR_3_PIN IO_24_PIN

#define BUTTON_FLOOR_4_PORT IO_25_PORT
#define BUTTON_FLOOR_4_DIRECTION IO_25_DIRECTION
#define BUTTON_FLOOR_4_INPUT IO_25_INPUT
#define BUTTON_FLOOR_4_PIN IO_25_PIN

#define BUTTON_FLOOR_5_PORT IO_26_PORT
#define BUTTON_FLOOR_5_DIRECTION IO_26_DIRECTION
#define BUTTON_FLOOR_5_INPUT IO_26_INPUT
#define BUTTON_FLOOR_5_PIN IO_26_PIN

#define LED_FLOOR_1_PORT IO_33_PORT
#define LED_FLOOR_1_DIRECTION IO_33_DIRECTION
#define LED_FLOOR_1_INPUT IO_33_INPUT
#define LED_FLOOR_1_PIN IO_33_PIN

#define LED_FLOOR_2_PORT IO_34_PORT
#define LED_FLOOR_2_DIRECTION IO_34_DIRECTION
#define LED_FLOOR_2_INPUT IO_34_INPUT
#define LED_FLOOR_2_PIN IO_34_PIN

#define LED_FLOOR_3_PORT IO_35_PORT
#define LED_FLOOR_3_DIRECTION IO_35_DIRECTION
#define LED_FLOOR_3_INPUT IO_35_INPUT
#define LED_FLOOR_3_PIN IO_35_PIN

#define LED_FLOOR_4_PORT IO_36_PORT
#define LED_FLOOR_4_DIRECTION IO_36_DIRECTION
#define LED_FLOOR_4_INPUT IO_36_INPUT
#define LED_FLOOR_4_PIN IO_36_PIN

#define LED_FLOOR_5_PORT IO_37_PORT
#define LED_FLOOR_5_DIRECTION IO_37_DIRECTION
#define LED_FLOOR_5_INPUT IO_37_INPUT
#define LED_FLOOR_5_PIN IO_37_PIN

// Movement & Doors LEDs mappings:

#define LED_DOORS_PORT IO_32_PORT
#define LED_DOORS_DIRECTION IO_32_DIRECTION
#define LED_DOORS_INPUT IO_32_INPUT
#define LED_DOORS_PIN IO_32_PIN

#define LED_MOVEMENT_PORT IO_31_PORT
#define LED_MOVEMENT_DIRECTION IO_31_DIRECTION
#define LED_MOVEMENT_INPUT IO_31_INPUT
#define LED_MOVEMENT_PIN IO_31_PIN

/////////////////////////////////

// Changed as in the project description it must be able to use floor 0
#define MIN_FLOOR (0)
#define MAX_FLOOR (99)

void init_avr_gpio_pins(void);

extern avr_gpio_t floor_buttons[MAX_FLOOR-MIN_FLOOR+1];
extern avr_gpio_t floor_leds[MAX_FLOOR-MIN_FLOOR+1];
extern avr_gpio_t doors_led;
extern avr_gpio_t movement_led;

#endif
